//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IceSubs
{
    using System;
    using System.Collections.Generic;
    
    public partial class IceUser
    {
        public IceUser()
        {
            this.Comments = new HashSet<Comment>();
            this.Media = new HashSet<Medium>();
            this.SuggestMedias = new HashSet<SuggestMedia>();
            this.Translations = new HashSet<Translation>();
            this.TranslationLines = new HashSet<TranslationLine>();
        }
    
        public int IceUserID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public Nullable<int> Achievements { get; set; }
        public Nullable<System.DateTime> Age { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Medium> Media { get; set; }
        public virtual ICollection<SuggestMedia> SuggestMedias { get; set; }
        public virtual ICollection<Translation> Translations { get; set; }
        public virtual ICollection<TranslationLine> TranslationLines { get; set; }
    }
}
