//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IceSubs
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IceSubsContext1 : DbContext
    {
        public IceSubsContext1()
            : base("name=IceSubsContext1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<IceUser> IceUsers { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Medium> Media { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<RequestTranslation> RequestTranslations { get; set; }
        public virtual DbSet<SuggestMedia> SuggestMedias { get; set; }
        public virtual DbSet<Translation> Translations { get; set; }
        public virtual DbSet<TranslationLine> TranslationLines { get; set; }
    }
}
