//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IceSubs
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestTranslation
    {
        public RequestTranslation()
        {
            this.SuggestMedias = new HashSet<SuggestMedia>();
        }
    
        public int RequestTranslationID { get; set; }
        public Nullable<int> UpVotes { get; set; }
        public int MediaID { get; set; }
    
        public virtual Medium Medium { get; set; }
        public virtual ICollection<SuggestMedia> SuggestMedias { get; set; }
    }
}
