//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IceSubs
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranslationLine
    {
        public int TranslationLinesID { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int Chapter { get; set; }
        public string Text { get; set; }
        public int TranslationID { get; set; }
        public int IceUserID { get; set; }
    
        public virtual IceUser IceUser { get; set; }
        public virtual Translation Translation { get; set; }
    }
}
